### ISSUE TITLE
how to interpret the figure in 5.1 and 5.4.

### ISSUE THREAD

**Issue by woodoo46** [arnederoeck/NanoSatellite#12]
Hi, 

I am just wondering how I can interpret the figure in your section 5.1 and 5.4. I mean what the x-axis and y-axis represent? How are they related to the repeat change?

Thanks.

George

**Comment by arnederoeck** [comment]
Hi,

The axes in 5.1 correspond to the distance that is generated after DTW alignment. Hence, smaller distances correspond to larger similarities between two signals. The y-axis corresponds to separation of flanking sequence and TR sequence in the squiggle, the x-axis denotes how well the TR is split into individual TR units.

In 5.4, the x-axis corresponds to a series of time points at which a current signal was measured (typically the ASIC in ONT sequencing captures 4000 current measurements per second). The y-axis is the corresponding z-scaled current measurement.

Best,
Arne
