### ISSUE TITLE
Empty fast5_index file

### ISSUE THREAD

**Issue by Tine-dk** [arnederoeck/NanoSatellite#14]
Hi,

At step 2 I use the summary file from an ONT run ending with "sequencing_summary.txt" (PCT0208_20191125_145249_PAE16041_promethion_sequencing_run_04284circulomic_sequencing_summary.txt). 

The script runs without errors but gives a file on 1 KB.

Is this the right type of summary file? And if so, do you have any idea why the output is empty?

Command:
`bash fast5_indexing.sh PCT0208_20191125_145249_PAE16041_promethion_sequencing_run_04284cirulomic_sequencing_summary.tsv /path/fast5 test
`

**Comment by arnederoeck** [comment]
Hi Tine, unfortunately I am no longer working with ONT data and I have not been working with recent ONT output files. Hence, possibly your files are no longer compatible with this tool. This tool was written two years ago, in a time where base calling issues were a bigger problem. Currently, however, ONT technology has progressed and I have not been able to adapt it accordingly. Hence I would advice against using NanoSatellite. Have you been looking at other tools for tandem repeats? (e.g. tandem-genotypes?).

Cheers,
Arne

**Comment by wdecoster** [comment]
These tools look also promising: 

- https://github.com/davidebolo1993/TRiCoLOR (genotyping)
- https://github.com/giesselmann/STRique (in-depth evaluation using signal data)

**Comment by Tine-dk** [comment]
Hi Arne,

Thank you for your fast reply.
ONT is really changing rapidly, so it's definitely understandable that new files might not work with NanoSatellite. Though, of course, it would have been very nice if they did.

I have tried NanoSTRique and it seems promising. For my project (masters thesis) I'm comparing different tools for counting tandem repeats, which is why I'm interested in making as many programs work as possible. So thank you very much for your program suggestions - I haven't heard about Tricolors and will take a look on it. 😃

Hope you are well,
Best regards, Tine



________________________________
Fra: arnederoeck <notifications@github.com>
Sendt: 2. juli 2020 09:46
Til: arnederoeck/NanoSatellite <NanoSatellite@noreply.github.com>
Cc: Tine <taine@live.dk>; Author <author@noreply.github.com>
Emne: Re: [arnederoeck/NanoSatellite] Empty fast5_index file (#14)


Hi Tine, unfortunately I am no longer working with ONT data and I have not been working with recent ONT output files. Hence, possibly your files are no longer compatible with this tool. This tool was written two years ago, in a time where base calling issues were a bigger problem. Currently, however, ONT technology has progressed and I have not been able to adapt it accordingly. Hence I would advice against using NanoSatellite. Have you been looking at other tools for tandem repeats? (e.g. tandem-genotypes?).

Cheers,
Arne
