### ISSUE TITLE
summary file for fast5_indexing.sh

### ISSUE THREAD

**Issue by rainwala** [arnederoeck/NanoSatellite#3]
Hello,

I'm trying to use your software with data generated by the latest version of MinKNOW on the MinION. However, I can't find a file called summary.tsv to use for the fast5_indexing script. I don't think the basecalling software generates that anymore. How might I obtain the summary file, or is there a way to generate the file or to use fast5_indexing.sh without the summary file?

Thanks.

**Comment by arnederoeck** [comment]
Hi, my apologies for the delayed response. I think there are two ways to solve this:
1. You can rebasecall the fast5 data using albacore, this will generate the summary file.
2. I now also added an extra piece of code (no_summary_indices.sh), which will generate the index without a summary file. It is slower than the original method and has some extra dependencies, but it should do the trick. I added information on how to use this in section 2.2 of the README file.

I hope this helps!

**Comment by rainwala** [comment]
No worries, thank you, I'll give this a try.
